language: rust
sudo: false

services:
  - redis-server

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add clippy-preview

script:
  - cargo clippy
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose

cache: cargo
